In [2]:
pip install nltk

Collecting nltk
  Downloading nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting click (from nltk)
  Downloading click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: joblib in c:\users\aishwarya\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.4.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2024.11.6-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\aishwarya\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------- ----- 1.3/1.5 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 5.4 MB/s eta 0:00:00
Downloading regex-2024.11.6-cp313-cp313-win_amd64.whl (273 kB)
Downloading click-8.1.8-py3-none-any.whl (98 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, click, nltk
Successfully installed click-8.1.8 nltk-3.9.1 regex-2024.11.6 tqdm-4.67.1
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install spacy

Collecting spacy
  Downloading spacy-3.8.2.tar.gz (1.3 MB)
     ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
     ---------------- ----------------------- 0.5/1.3 MB 4.6 MB/s eta 0:00:01
     ------------------------ --------------- 0.8/1.3 MB 2.8 MB/s eta 0:00:01
     ---------------------------------------- 1.3/1.3 MB 2.0 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [557 lines of output]
      Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
      Collecting setuptools
        Downloading setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
      Collecting cython<3.0,>=0.25
        Downloading Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
      Collecting cymem<2.1.0,>=2.0.2
        Downloading cymem-2.0.11-cp313-cp313-win_amd64.whl.metadata (8.8 kB)
      Collecting preshed<3.1.0,>=3.0.2
        Downloading preshed-3.0.9.tar.gz (14 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting murmurhash<1.1.0,>=0.28.0
        Using cached murmurhash-1.0.12-cp313-cp313-win_amd64.whl.metadata (2.2 kB)
      Collecting thinc<8.4.0,>=8.3.0
        Downloading thinc-8.3.2.tar.gz (193 kB)
        Installing build dependencies: started
        Installing build dependencies: still running...
        Installing build dependencies: still running...
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error

        Ã— pip subprocess to install build dependencies did not run successfully.
        â”‚ exit code: 1
        â•°â”€> [519 lines of output]
            Ignoring numpy: markers 'python_version < "3.9"' don't match your environment
            Collecting setuptools
              Using cached setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
            Collecting cython<3.0,>=0.25
              Using cached Cython-0.29.37-py2.py3-none-any.whl.metadata (3.1 kB)
            Collecting murmurhash<1.1.0,>=1.0.2
              Using cached murmurhash-1.0.12-cp313-cp313-win_amd64.whl.metadata (2.2 kB)
            Collecting cymem<2.1.0,>=2.0.2
              Using cached cymem-2.0.11-cp313-cp313-win_amd64.whl.metadata (8.8 kB)
            Collecting preshed<3.1.0,>=3.0.2
              Using cached preshed-3.0.9.tar.gz (14 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting blis<1.1.0,>=1.0.0
              Downloading blis-1.0.2-cp313-cp313-win_amd64.whl.metadata (7.8 kB)
            Collecting numpy<2.1.0,>=2.0.0
              Downloading numpy-2.0.2.tar.gz (18.9 MB)
                 ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
                 ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
                 ---------------------------------------- 0.0/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                  --------------------------------------- 0.3/18.9 MB ? eta -:--:--
                 - ------------------------------------- 0.5/18.9 MB 109.0 kB/s eta 0:02:49
                 - ------------------------------------- 0.5/18.9 MB 109.0 kB/s eta 0:02:49
                 - ------------------------------------- 0.5/18.9 MB 109.0 kB/s eta 0:02:49
                 - ------------------------------------- 0.5/18.9 MB 109.0 kB/s eta 0:02:49
                 - ------------------------------------- 0.5/18.9 MB 109.0 kB/s eta 0:02:49
                 - ------------------------------------- 0.5/18.9 MB 109.0 kB/s eta 0:02:49
                 - ------------------------------------- 0.5/18.9 MB 109.0 kB/s eta 0:02:49
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 - ------------------------------------- 0.8/18.9 MB 135.1 kB/s eta 0:02:15
                 -- ------------------------------------ 1.0/18.9 MB 124.3 kB/s eta 0:02:24
                 -- ------------------------------------ 1.0/18.9 MB 124.3 kB/s eta 0:02:24
                 -- ------------------------------------ 1.0/18.9 MB 124.3 kB/s eta 0:02:24
                 -- ------------------------------------ 1.0/18.9 MB 124.3 kB/s eta 0:02:24
                 -- ------------------------------------ 1.0/18.9 MB 124.3 kB/s eta 0:02:24
                 -- ------------------------------------ 1.0/18.9 MB 124.3 kB/s eta 0:02:24
                 -- ------------------------------------ 1.0/18.9 MB 124.3 kB/s eta 0:02:24
                 -- ------------------------------------ 1.0/18.9 MB 124.3 kB/s eta 0:02:24
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 -- ------------------------------------ 1.3/18.9 MB 130.2 kB/s eta 0:02:16
                 --- ----------------------------------- 1.6/18.9 MB 127.5 kB/s eta 0:02:16
                 --- ----------------------------------- 1.6/18.9 MB 127.5 kB/s eta 0:02:16
                 --- ----------------------------------- 1.6/18.9 MB 127.5 kB/s eta 0:02:16
                 --- ----------------------------------- 1.6/18.9 MB 127.5 kB/s eta 0:02:16
                 --- ----------------------------------- 1.6/18.9 MB 127.5 kB/s eta 0:02:16
                 --- ----------------------------------- 1.6/18.9 MB 127.5 kB/s eta 0:02:16
                 --- ----------------------------------- 1.8/18.9 MB 136.3 kB/s eta 0:02:06
                 --- ----------------------------------- 1.8/18.9 MB 136.3 kB/s eta 0:02:06
                 --- ----------------------------------- 1.8/18.9 MB 136.3 kB/s eta 0:02:06
                 --- ----------------------------------- 1.8/18.9 MB 136.3 kB/s eta 0:02:06
                 --- ----------------------------------- 1.8/18.9 MB 136.3 kB/s eta 0:02:06
                 ---- ---------------------------------- 2.1/18.9 MB 146.2 kB/s eta 0:01:55
                 ---- ---------------------------------- 2.1/18.9 MB 146.2 kB/s eta 0:01:55
                 ---- ---------------------------------- 2.1/18.9 MB 146.2 kB/s eta 0:01:55
                 ---- ---------------------------------- 2.1/18.9 MB 146.2 kB/s eta 0:01:55
                 ---- ---------------------------------- 2.4/18.9 MB 156.1 kB/s eta 0:01:46
                 ---- ---------------------------------- 2.4/18.9 MB 156.1 kB/s eta 0:01:46
                 ---- ---------------------------------- 2.4/18.9 MB 156.1 kB/s eta 0:01:46
                 ---- ---------------------------------- 2.4/18.9 MB 156.1 kB/s eta 0:01:46
                 ----- --------------------------------- 2.6/18.9 MB 165.1 kB/s eta 0:01:39
                 ----- --------------------------------- 2.6/18.9 MB 165.1 kB/s eta 0:01:39
                 ----- --------------------------------- 2.6/18.9 MB 165.1 kB/s eta 0:01:39
                 ----- --------------------------------- 2.6/18.9 MB 165.1 kB/s eta 0:01:39
                 ----- --------------------------------- 2.6/18.9 MB 165.1 kB/s eta 0:01:39
                 ----- --------------------------------- 2.6/18.9 MB 165.1 kB/s eta 0:01:39
                 ----- --------------------------------- 2.6/18.9 MB 165.1 kB/s eta 0:01:39
                 ----- --------------------------------- 2.6/18.9 MB 165.1 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ----- --------------------------------- 2.9/18.9 MB 162.8 kB/s eta 0:01:39
                 ------ -------------------------------- 3.1/18.9 MB 153.6 kB/s eta 0:01:43
                 ------ -------------------------------- 3.1/18.9 MB 153.6 kB/s eta 0:01:43
                 ------ -------------------------------- 3.1/18.9 MB 153.6 kB/s eta 0:01:43
                 ------ -------------------------------- 3.1/18.9 MB 153.6 kB/s eta 0:01:43
                 ------ -------------------------------- 3.1/18.9 MB 153.6 kB/s eta 0:01:43
                 ------- ------------------------------- 3.4/18.9 MB 159.7 kB/s eta 0:01:38
                 ------- ------------------------------- 3.4/18.9 MB 159.7 kB/s eta 0:01:38
                 ------- ------------------------------- 3.4/18.9 MB 159.7 kB/s eta 0:01:38
                 ------- ------------------------------- 3.4/18.9 MB 159.7 kB/s eta 0:01:38
                 ------- ------------------------------- 3.4/18.9 MB 159.7 kB/s eta 0:01:38
                 ------- ------------------------------- 3.4/18.9 MB 159.7 kB/s eta 0:01:38
                 ------- ------------------------------- 3.4/18.9 MB 159.7 kB/s eta 0:01:38
                 ------- ------------------------------- 3.7/18.9 MB 161.1 kB/s eta 0:01:35
                 ------- ------------------------------- 3.7/18.9 MB 161.1 kB/s eta 0:01:35
                 ------- ------------------------------- 3.7/18.9 MB 161.1 kB/s eta 0:01:35
                 ------- ------------------------------- 3.7/18.9 MB 161.1 kB/s eta 0:01:35
                 ------- ------------------------------- 3.7/18.9 MB 161.1 kB/s eta 0:01:35
                 ------- ------------------------------- 3.7/18.9 MB 161.1 kB/s eta 0:01:35
                 ------- ------------------------------- 3.7/18.9 MB 161.1 kB/s eta 0:01:35
                 ------- ------------------------------- 3.7/18.9 MB 161.1 kB/s eta 0:01:35
                 ------- ------------------------------- 3.7/18.9 MB 161.1 kB/s eta 0:01:35
                 ------- ------------------------------- 3.7/18.9 MB 161.1 kB/s eta 0:01:35
                 -------- ------------------------------ 3.9/18.9 MB 157.0 kB/s eta 0:01:36
                 -------- ------------------------------ 3.9/18.9 MB 157.0 kB/s eta 0:01:36
                 -------- ------------------------------ 3.9/18.9 MB 157.0 kB/s eta 0:01:36
                 -------- ------------------------------ 3.9/18.9 MB 157.0 kB/s eta 0:01:36
                 -------- ------------------------------ 3.9/18.9 MB 157.0 kB/s eta 0:01:36
                 -------- ------------------------------ 3.9/18.9 MB 157.0 kB/s eta 0:01:36
                 -------- ------------------------------ 4.2/18.9 MB 159.8 kB/s eta 0:01:33
                 -------- ------------------------------ 4.2/18.9 MB 159.8 kB/s eta 0:01:33
                 --------- ----------------------------- 4.5/18.9 MB 168.2 kB/s eta 0:01:26
                 --------- ----------------------------- 4.7/18.9 MB 176.9 kB/s eta 0:01:21
                 --------- ----------------------------- 4.7/18.9 MB 176.9 kB/s eta 0:01:21
                 ---------- ---------------------------- 5.0/18.9 MB 183.8 kB/s eta 0:01:16
                 ---------- ---------------------------- 5.0/18.9 MB 183.8 kB/s eta 0:01:16
                 ---------- ---------------------------- 5.0/18.9 MB 183.8 kB/s eta 0:01:16
                 ---------- ---------------------------- 5.0/18.9 MB 183.8 kB/s eta 0:01:16
                 ---------- ---------------------------- 5.0/18.9 MB 183.8 kB/s eta 0:01:16
                 ---------- ---------------------------- 5.0/18.9 MB 183.8 kB/s eta 0:01:16
                 ---------- ---------------------------- 5.0/18.9 MB 183.8 kB/s eta 0:01:16
                 ---------- ---------------------------- 5.2/18.9 MB 183.4 kB/s eta 0:01:15
                 ---------- ---------------------------- 5.2/18.9 MB 183.4 kB/s eta 0:01:15
                 ---------- ---------------------------- 5.2/18.9 MB 183.4 kB/s eta 0:01:15
                 ---------- ---------------------------- 5.2/18.9 MB 183.4 kB/s eta 0:01:15
                 ---------- ---------------------------- 5.2/18.9 MB 183.4 kB/s eta 0:01:15
                 ---------- ---------------------------- 5.2/18.9 MB 183.4 kB/s eta 0:01:15
                 ----------- --------------------------- 5.5/18.9 MB 184.4 kB/s eta 0:01:13
                 ----------- --------------------------- 5.5/18.9 MB 184.4 kB/s eta 0:01:13
                 ----------- --------------------------- 5.5/18.9 MB 184.4 kB/s eta 0:01:13
                 ----------- --------------------------- 5.8/18.9 MB 190.4 kB/s eta 0:01:09
                 ----------- --------------------------- 5.8/18.9 MB 190.4 kB/s eta 0:01:09
                 ----------- --------------------------- 5.8/18.9 MB 190.4 kB/s eta 0:01:09
                 ----------- --------------------------- 5.8/18.9 MB 190.4 kB/s eta 0:01:09
                 ----------- --------------------------- 5.8/18.9 MB 190.4 kB/s eta 0:01:09
                 ------------ -------------------------- 6.0/18.9 MB 199.4 kB/s eta 0:01:05
                 ------------ -------------------------- 6.0/18.9 MB 199.4 kB/s eta 0:01:05
                 ------------ -------------------------- 6.0/18.9 MB 199.4 kB/s eta 0:01:05
                 ------------ -------------------------- 6.3/18.9 MB 203.7 kB/s eta 0:01:02
                 ------------ -------------------------- 6.3/18.9 MB 203.7 kB/s eta 0:01:02
                 ------------ -------------------------- 6.3/18.9 MB 203.7 kB/s eta 0:01:02
                 ------------- ------------------------- 6.6/18.9 MB 208.6 kB/s eta 0:01:00
                 ------------- ------------------------- 6.6/18.9 MB 208.6 kB/s eta 0:01:00
                 -------------- ------------------------ 6.8/18.9 MB 215.4 kB/s eta 0:00:57
                 -------------- ------------------------ 6.8/18.9 MB 215.4 kB/s eta 0:00:57
                 -------------- ------------------------ 7.1/18.9 MB 221.5 kB/s eta 0:00:54
                 -------------- ------------------------ 7.1/18.9 MB 221.5 kB/s eta 0:00:54
                 -------------- ------------------------ 7.1/18.9 MB 221.5 kB/s eta 0:00:54
                 --------------- ----------------------- 7.3/18.9 MB 227.4 kB/s eta 0:00:51
                 --------------- ----------------------- 7.3/18.9 MB 227.4 kB/s eta 0:00:51
                 --------------- ----------------------- 7.3/18.9 MB 227.4 kB/s eta 0:00:51
                 --------------- ----------------------- 7.3/18.9 MB 227.4 kB/s eta 0:00:51
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 --------------- ----------------------- 7.6/18.9 MB 230.1 kB/s eta 0:00:50
                 ---------------- ---------------------- 7.9/18.9 MB 230.4 kB/s eta 0:00:48
                 ---------------- ---------------------- 7.9/18.9 MB 230.4 kB/s eta 0:00:48
                 ---------------- ---------------------- 7.9/18.9 MB 230.4 kB/s eta 0:00:48
                 ---------------- ---------------------- 7.9/18.9 MB 230.4 kB/s eta 0:00:48
                 ---------------- ---------------------- 7.9/18.9 MB 230.4 kB/s eta 0:00:48
                 ---------------- ---------------------- 8.1/18.9 MB 235.6 kB/s eta 0:00:46
                 ---------------- ---------------------- 8.1/18.9 MB 235.6 kB/s eta 0:00:46
                 ---------------- ---------------------- 8.1/18.9 MB 235.6 kB/s eta 0:00:46
                 ---------------- ---------------------- 8.1/18.9 MB 235.6 kB/s eta 0:00:46
                 ---------------- ---------------------- 8.1/18.9 MB 235.6 kB/s eta 0:00:46
                 ----------------- --------------------- 8.4/18.9 MB 236.6 kB/s eta 0:00:45

In [5]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/singhrau0/Big-Data-Preprocessing/refs/heads/main/titanic_dataset.csv")
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\aishwarya\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aishwarya\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\aishwarya\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.5 MB 3.0 MB/s eta 0:00:04
   -------- ------------------------------- 2.4/11.5 MB 4.5 MB/s eta 0:00:03
   ------------ --------------------------- 3.7/11.5 MB 5.1 MB/s eta 0:00:02
   ------------- -------------------------- 3.9/11.5 MB 5.2 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.5 MB 4.2 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.5 MB 4.0 MB/s eta 0:00:02
   --------------------- ------------------ 6.3/11.5 MB 4.2 MB/s eta 0:00:02
   ----------------------- ---------------- 6.8/11.5 MB 3.7 MB/s eta 0:00:02
   ---------------------------------- ----- 10.0/11.5 MB 5.1 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.5 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.5 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 3.7 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2024.2 tzdata-2024.2
Note: you may need to restart the kernel to use updated packages.

In [6]:
#filter the data of male whose age greater than 50
df[(df['Gender']=='male') & (df['Age']>50)].count()

PassengerId    47
Survived       47
Pclass         47
Name           47
Gender         47
Age            47
SibSp          47
Parch          47
Ticket         47
Fare           47
Cabin          20
Embarked       47
dtype: int64

In [7]:
df[(df['Gender']=='male') & (df['Survived']==1)]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [8]:
df.loc[df['Age']>55, 'Fare']=500

In [9]:
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [10]:
df['Age']>55

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [14]:
#update fair values of p class 1 who have more than 4 sibsp
#df.loc[df[['Pclass']==1, df['SibSp']>4], 'Fare']=500

In [17]:
df[(df['Pclass']==1) & (df['SibSp']>2)]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0,C23 C25 C27,S

In [18]:
df.loc[(df['Pclass']==1) & (df['SibSp']>2), 'Fare']=1000

In [19]:
df[(df['Pclass']==1)&(df['Gender']=='female')]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,500.0000,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,500.0000,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [20]:
df.loc[(df['Pclass']==1)&(df['Gender']=='female'), 'Fare']*=1.3

In [22]:
df[(df['Pclass']==1)&(df['Gender']=='female')]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,92.66829,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,69.03000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,650.00000,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,190.47704,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,99.74796,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,214.32671,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,33.70796,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,68.32046,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,650.00000,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,39.00000,B42,S

In [23]:
df.loc[(df['Pclass']==1)&(df['Gender']=='female'), 'Fare']=df['Fare']*1.3

In [24]:
df[(df['Pclass']==1)&(df['Gender']=='female')]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,120.468777,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,89.739000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,845.000000,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,247.620152,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,129.672348,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,278.624723,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,43.820348,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,88.816598,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,845.000000,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,50.700000,B42,S

In [26]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [28]:
df[df['Age'].isnull()]

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [29]:
df.loc[df['Age'].isnull(), 'Age']=29.69

In [30]:
df[df['Age'].isnull()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Gender, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [31]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64